# Generated by Django 3.1.3 on 2020-11-29 01:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_task_completed'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='completed',
            new_name='complete',
        ),
    ]
